### ISSUE TITLE
Add support for OpenHistoricalMap

### ISSUE THREAD

**Issue by Dimitar5555** [tankaru/OpenSwitchMaps#100]
It uses the same schema as openstreetmap, but the domain is openhistoricalmap.org.

**Comment by tankarup** [comment]
openhistoricalmap is already implemented. please check.

**Comment by tankaru** [comment]
openhistoricalmap is already implemented. please check.

**Comment by Dimitar5555** [comment]
It is indeed implemented but for the `www.` version of the site. There is a missing redirect on `opnehistoricalmap.org` which I've just reported https://github.com/OpenHistoricalMap/issues/issues/508.
