### ISSUE TITLE
Support https://gpx.studio/

### ISSUE THREAD

**Issue by ravenfeld** [tankaru/OpenSwitchMaps#106]
Hello, is it possible to support gpx studio.

Thanks in advance

**Comment by tankaru** [comment]
It's not supported because gpx studio does not accept or return urls with lat/lon.

**Comment by limex** [comment]
You might want to Check out Bikerouter.de
Maybe it has all the features that you want , pllus exposes XYZ

**Comment by ravenfeld** [comment]
Thank you very much for your reply, I hadn't noticed. GpxStudio was in the middle of dev I'll see if it's planned.
