### ISSUE TITLE
Support for another google maps source

### ISSUE THREAD

**Issue by cpo-ux** [tankaru/OpenSwitchMaps#110]
I'd like the extension to be able to grab coordinates from this type of google maps link:

https://www.google.com/maps/d/u/0/viewer?mid=1EpC-GTEzYFLFL8kPS1kqT7znfsU&ll=61.19171304966161%2C-104.53748034782325&z=5

and with this type of link as well:
(same as above but with edit link instead of viewer link)
https://www.google.com/maps/d/u/0/edit?mid=1EpC-GTEzYFLFL8kPS1kqT7znfsU&ll=60.15967146110667%2C-98.33311078792674&z=9

**Comment by tankaru** [comment]
I will add the ll=* format for google maps.
