### ISSUE TITLE
Apple Maps link

### ISSUE THREAD

**Issue by cpo-ux** [tankaru/OpenSwitchMaps#111]
Hi, firstly this is a great extension, thanks a lot.

For apple maps links, I'd recommend this style of URL since it puts a marker on the map:
(and is more convenient to view so that when you pan on the map you can still see the location)

https://maps.apple.com/?q=81.673184,-120.798333

Presently the apple maps links provided is this style:
http://maps.apple.com/?ll=81.6731837,-120.7983332&z=7

Which centers the map on the point but no marker is placed.

Oh cool, just found out something, you can get apple maps to open on windows PC with this style of link:
(scroll zoom doesn't work so you have to use the + and - buttons for zoom)
https://maps.apple.com/place?ll=81.6731837,-120.7983332&q=[Whatever_string_of_text]
(however if you do it this way it will not open in Apple maps by default on iOS - but it will give you the option to open it in the Apple Maps app)

**Comment by tankaru** [comment]
The current policy is to convert pins to pins and map centres to map centres. Therefore, if a map is moved from a non-pinned map, it will not be pinned.
Anyway thank you for showing me how to pin on Apple Maps. I will add the feature.
