### ISSUE TITLE
ESRI hybrid map - Add map service please

### ISSUE THREAD

**Issue by cpo-ux** [tankaru/OpenSwitchMaps#113]
Very good source of map data:
(please add to list of map services in extension)
https://www.arcgis.com/home/webmap/viewer.html?webmap=86265e5a4bbb4187a59719cf134e0018

URL's work like this:
https://www.arcgis.com/home/webmap/viewer.html?webmap=86265e5a4bbb4187a59719cf134e0018&find={latitude},{longitude}

more info here:
https://www.esri.com/arcgis-blog/products/arcgis-online/mapping/use-url-parameters-in-map-viewer/

Thanks again :)

**Comment by tankaru** [comment]
Thanks.
I'll add this map.
