### ISSUE TITLE
Add Panoramax

### ISSUE THREAD

**Issue by charlesmillet** [tankaru/OpenSwitchMaps#114]
Hi,

Thank for this great and so usefull tool!

I would like to see Panoramax added to the list. There is curently two instances : panoramax.openstreetmap.fr and panoramax.ign.fr but https://panoramax.fr/photos is the global catalog.

It is a Mapillary alternative with a great futur. More information on https://panoramax.fr

Regards.

Charles

**Comment by tankaru** [comment]
Thanks. I'll support Panoramax.

**Comment by sylvain-m** [comment]
Panomarax has change the domain and URL synthax.
Here is the new domain :
https://api.panoramax.xyz
And an exemple of URL scheme :
https://api.panoramax.xyz/#focus=map&map=17.98/48.873712/2.295266&speed=250
