### ISSUE TITLE
Sentinel is now copernicus

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [tankaru/OpenSwitchMaps#118]
When you enter sentinel link it redirects to https://dataspace.copernicus.eu/browser/?zoom=18&lat=-2.51845&lng=-45.25338&themeId=DEFAULT-THEME&visualizationUrl=https%3A%2F%2Fsh.dataspace.copernicus.eu%2Fogc%2Fwms%2Fa91f72b5-f393-4320-bc0f-990129bd9e63&datasetId=S2_L2A_CDAS&fromTime=2023-05-13T00%3A00%3A00.000Z&toTime=2023-11-13T23%3A59%3A59.999Z&layerId=1_TRUE_COLOR&mosaickingOrder=mostRecent&demSource3D=%22MAPZEN%22&cloudCoverage=30&dateMode=MOSAIC

**Comment by tankaru** [comment]
Which map?
