### ISSUE TITLE
Support https://overpass-turbo.eu

### ISSUE THREAD

**Issue by Binnette** [tankaru/OpenSwitchMaps#120]
Hi @tankaru TY for this awesome extension! So usefull!

Can you please "support" https://overpass-turbo.eu? I mean can you please "activate" your extension when my browser is on https://overpass-turbo.eu? That way, I can easily swith from Overpass-Turbo to other maps.

Currently when I am on https://overpass-turbo.eu and I click on the extension, it show a message like "OpenSwitchMaps can not read or edit data from this website". Also the extension logo is not shown in the adresse bar.

Have a nice day.

**Comment by tankaru** [comment]
https://overpass-turbo.eu/ doesn't give me its location, so I can't support it.
