### ISSUE TITLE
view-source: URLs handling / Hangs Firefox extensions and hogs CPU for dozens of seconds on "view selection source"

### ISSUE THREAD

**Issue by Self-Perfection** [tankaru/OpenSwitchMaps#125]
Steps to reproduce:

1. Launch Firefox with new empty profile (e.g. `firefox  -ProfileManager`)
2. Install OpenSwitchMaps extension
3. Navigate to URL https://alexanderwales.com/worth-the-candle-ch-118/
4. Select text from "“That’s good background, thank you,” said Amaryllis." till "“You could trust us a little bit,” said Pallida. " (This is quite specific, yes, but I have noticed at another pages as well)
5. In context menu launch "View selection source"
6. Notice that though Firefox is responsive it consumes whole CPU core for about 30 sec. Here is recorded profile which shows that CPU is consumed by OpenSwitchMaps: https://share.firefox.dev/3wuvSGw

I suppose extension is trying to find geo coordinates within long `view-source:` URI. In my example this URI is more than 60k chars.
And therefore solution should be skipping `view-source:` URI from parsing. Or even better: just do nothing on websites that are not supported.

**Comment by tankaru** [comment]
Thanks. I'll fix that.

**Comment by tankaru** [comment]
I published version 1.5.4 to fix this issue.
