### ISSUE TITLE
Add-on button does not appear in firefox

### ISSUE THREAD

**Issue by Self-Perfection** [tankaru/OpenSwitchMaps#13]
I use Firefox 66.0.3 on Arch linux.

I've installed addon, but there is no visible ways to interact with it.

How can I debug this?

**Comment by Self-Perfection** [comment]
Ahhh, got it finally! Button appears in URL bar! https://addons.mozilla.org/en-GB/firefox/addon/openswitchmaps/ show wrong screenshot, from version for chromium. That was misleading for me. Pls replace screenshot.

**Comment by tankaru** [comment]
Ah, right. That's a screenshot of Chrome extension. I'll replace it.

**Comment by tankaru** [comment]
Updated a screenshot
