### ISSUE TITLE
French GeoPortal (IGN) Link

### ISSUE THREAD

**Issue by sylvain-m** [tankaru/OpenSwitchMaps#15]
First and foremost, I want to congratulate you for this great extension that I have been using since yesterday and that fills an almost every day need (as a cartographer).

As a French, the national cartographic reference is IGN GeoPortal : https://www.geoportail.gouv.fr/

It would be really great to be able to switch to the Geoportal from a Google map (reciprocally too, whatever it is less useful for my use).

The Geoportal's URLs are constructed as follows:
`https://www.geoportail.gouv.fr/carte?c={long},{lat}&z={zoom}&l0={layer(s)}&permalink=yes`
Which gives for example:
`https://www.geoportail.gouv.fr/carte?c=-0.7565114253448404,48.479766077662816&z=15&l0=GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN25TOUR.CV::GEOPORTAIL:OGC:WMTS(1)&permalink=yes`
[link](https://www.geoportail.gouv.fr/carte?c=-0.7565114253448404,48.479766077662816&z=15&l0=GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN25TOUR.CV::GEOPORTAIL:OGC:WMTS(1)&permalink=yes)
(topographic map "Scan 25")

Do you think it would be possible to add this link?

If it's a too specific use, maybe it would be possible to create a "forked plugin" for French users ?

**Comment by tankaru** [comment]
I've added IGN GeoPortal on "other maps". 
However you can't go back from IGN GeoPortal, because it doesn't update URL.

At this time I don't have decided whether to make forked plugins or  not.
But I don't want to too much inflate the menu at least.

**Comment by tankaru** [comment]
Actually I don't know what options are available, because I'm not an IT engineer.

Any proposals are welcome.

**Comment by sylvain-m** [comment]
> I've added IGN GeoPortal on "other maps".

Great !!!
thank you so much

> However you can't go back from IGN GeoPortal, because it doesn't update URL.

Yes, I noticed, and I suspected it would be impossible. Not important, as I said, it's less useful.

>  But I don't want to too much inflate the menu at least.

Yes I understand.
The French thank you then!

> because I'm not an IT engineer.

Neither do I...
So, I congratulate you all the more for this plugin :smiley:

**Comment by Bibi56** [comment]
Ideally, your plugin would behave like ID or JOSM: take into account the position to propose the most meaningful providers. For instance IGN GeoPortal is excellent for France, outside France comparatively poor so a few bounding boxes could help.
See https://github.com/osmlab/editor-layer-index, more precisely in https://raw.githubusercontent.com/osmlab/editor-layer-index/gh-pages/imagery.xml (or .json or .geojson) to see if one of those types is easy to use for you. At least you can use the polygons as it defines the validity of the provider for the area (BDOrtho has the same extent as IGN GeoPortal).

As I said _ideally_ ;-). Congrats too.

**Comment by tankaru** [comment]
>to propose the most meaningful providers
It's a good idea. Unfortunately I don't know what to do at all. Maybe it is a future plan.
