### ISSUE TITLE
Link to Qwant Maps

### ISSUE THREAD

**Issue by sylvain-m** [tankaru/OpenSwitchMaps#16]
The [Qwant Maps](https://www.qwant.com/maps/) service offers vector tiles based on OpenStreetMap.
Unless I'm mistaken, there are no other services based on vector data among the extension proposed links : this could be interesting to add because the URLs are very simple:
https://www.qwant.com/maps/#map={zoom}/{lat}/{long}
[example](https://www.qwant.com/maps/#map=10.00/48.4799961/-0.7579478)

**Comment by tankaru** [comment]
Agree. 
I will put it on Main map.

**Comment by tankaru** [comment]
done
