### ISSUE TITLE
Switch embedded maps

### ISSUE THREAD

**Issue by picsi** [tankaru/OpenSwitchMaps#18]
It would be great if this map could switch slippy maps embedded in a page. I'd love to have OSM maps always loaded by default instead of Google Maps, for instance.

**Comment by tankaru** [comment]
Currently there is no plan to support embedded map.

However your idea sounds interesting to me, so I made a simple and experimental Chrome extension to replace embedded Google map to OpenStreetMap, just for testing.
https://github.com/tankaru/ReplaceG2O

You can modify, upgrade, publish it if you want.

**Comment by picsi** [comment]
Thank you! That sounds great. Would it be possible to make a Firefox version? It's what I'm using.

**Comment by tankaru** [comment]
Sorry I don't know how to do it.
Firefox support is completely developed by jazzzz, not me.

**Comment by picsi** [comment]
@jazzzz ping

**Comment by jazzzz** [comment]
I can try to port the extension, but it is quite limited because it only works for maps embedded with an iframe, it seems to me that most embedded Google maps are embedded via the API.

**Comment by jazzzz** [comment]
I ported it to Firefox (tankaru/ReplaceG2O#1), but I could not find a real page with an embedded map to test it.

**Comment by picsi** [comment]
Thank you! It's a nice start. If we can get the API switched, that'd be amazing.

**Comment by Bibi56** [comment]
@jazzzz I found such a page some weeks ago and I confirm: it works!
