### ISSUE TITLE
Don't work for openstreetmap nodes or ways 

### ISSUE THREAD

**Issue by pyrog** [tankaru/OpenSwitchMaps#20]
https://www.openstreetmap.org/way/686514329 or [node/686514329](https://www.openstreetmap.org/node/686514329) don't work.

https://www.openstreetmap.org/way/686514329#map=19/52.20990/4.94243 work fine.

The html code of the osm webpage contain the coordinates of the bounding box:
```html
<head
    data-locale="fr"
    data-preferred-editor="id"
    data-location="{&quot;minlon&quot;:-5.142222,&quot;minlat&quot;:41.371582,&quot;maxlon&quot;:9.561556,&quot;maxlat&quot;:51.092804}"
>
```

**Comment by tankaru** [comment]
Thanks a lot. I didn't know OSM webpage source code contains lat/lon. But unfortunately I don't know a good way to get them. If I will do it, I may rewrite all code.

**Comment by pyrog** [comment]
> The html code of the osm webpage contain the coordinates of the bounding box

The box is too "large".

Better, we could get the coordinates of the node or way:
```html
<div id="sidebar_content">
<h2>
  <a class="geolink" href="https://www.openstreetmap.org/#map=15/46.3653/5.7605"><span class="icon close"></span></a>
  Way : 681898310
</h2>
```

To extract it:
```javascript
url = document.getElementsByClassName("geolink")[0].getAttribute("href");
```

**Comment by tankaru** [comment]
With my PC, I can't get html code like
 `<a class="geolink" href="https://www.openstreetmap.org/#map=15/46.3653/5.7605"><span class="icon close"></span></a>`
from https://www.openstreetmap.org/way/681898310

I don't know why.

**Comment by tankaru** [comment]
And bounding box in the 'data-location' is not the location of the object, I think.

**Comment by pyrog** [comment]
Tested with Chrome, Firefox and Safari under mac OS, I get `<a class="geolink" href="https://www.openstreetmap.org/#map=15/46.3653/5.7605">`

Will check later under Ubuntu…

**Comment by tankaru** [comment]
With my PC (Windows10, Chrome) it shows like this

```
<div id="sidebar_content">
<h2>
<a class="geolink" href="/"><span class="icon close"></span></a>
Way : 681898310
</h2>
```

**Comment by Bibi56** [comment]
@tankaru , I checked on Win 8.1, FF and MSIE: I think I had seen what @pyrog said but now I try and I don't get it. It may get added only in certain circumstances or by some plug-ins. @pyrog can you deactivate all your plug-ins? Did you try in your different browsers?
