### ISSUE TITLE
How to debug OpenSwitchMaps?

### ISSUE THREAD

**Issue by pyrog** [tankaru/OpenSwitchMaps#21]
Hi,

I forked your project, git clone it to my computer.
With Firefox, follow [Your first extension](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension).
And with Chrome / Chromium, follow [Create and publish custom Chrome apps & extensions](https://support.google.com/chrome/a/answer/2714278?hl=en).

Unfortunately OpenSwitchMaps icon is displayed in gray.

Tested under Ubuntu and macOS

![Chrome](https://user-images.githubusercontent.com/2158081/65311207-30ae1780-db90-11e9-8732-95fa07bd9e26.jpeg)
![Firefox](https://user-images.githubusercontent.com/2158081/65311209-3146ae00-db90-11e9-9a67-d53f96599fa9.jpeg)

**Comment by Bibi56** [comment]
@pyrog, did you move from the initial place (i.e. do you have #map=) in the url? If not it's normal.

**Comment by pyrog** [comment]
Of course 😉

**Comment by Bibi56** [comment]
then probably like me you selected the wrong directory: add manifest.json from the dist directory. Then it works. I think you can close the ticket ;-)

**Comment by pyrog** [comment]
I copied all the file (without any modification) to a local directory i.e. `/home/pyrog/OpenSwitchMaps` and from Chrome -> [chrome://extensions/](chrome://extensions/) -> Load Unpacked

It display "ReferenceError: require is not defined"
require is defined in node.js, not in javascript 😉.

An add-on is written in javascript, not node.js.

If I copy and adapt the content of maps.js in background.js and popup.js, it works 😄 

background.js
//const maps = require('./maps');

maps = [{
    name: "Google Maps",
    category: "Main maps",
    domain: "www.google.com",

**Comment by Bibi56** [comment]
Again, if you have `const maps = require('./maps');` in `background.js`, that's because you loaded the source directory, you should load the `dist` dub-directory instead.

**Comment by pyrog** [comment]
Ok, thanks.

I missed an important step : building the extension into the `dist` directory.
`npm run build`
