### ISSUE TITLE
Add an expert mode to customise OpenSwitchMaps

### ISSUE THREAD

**Issue by pyrog** [tankaru/OpenSwitchMaps#22]
Something like this will be useful : https://mc.bbbike.org/mc/console.html

**Comment by tankaru** [comment]
Currently I don't have a plan to show several maps in one window.

I like Map compare and Multimapas for those usage.
Multimapas: http://javier.jimenezshaw.com/mapas/mapas.html

**Comment by pyrog** [comment]
The idea is not to compare several maps (I discovered [Multimapas](http://javier.jimenezshaw.com/mapas/?c=43.0029563,6.2023026&z=17&f=osm_wm&b=esri-sat&v=3&e=0.5&o=100&ed=0&m=&ga=0) with your addon :sunglasses: ).
I want to add something to show/hide/organize maps already coded in the addon, and add new ones (just the url, the "wizard" see #11 could guess how to find lat,lon and zoom).

For example:
* European users don't need Japanese maps and vice-versa
* Sailors could need to see only some
* ...

**Comment by tankaru** [comment]
I understand. And I agree with you. I want to personalize map list.

However I cannot do it because of my poor programming skill.

**Comment by jazzzz** [comment]
I wanted to do this when I have some time, but unfortunately I could not find the time...

**Comment by tankaru** [comment]
jazzzz made a great contribution again implementing settings to show/hide map items.
Thanks!

**Comment by pyrog** [comment]
#27
Thank you 😄

**Comment by jazzzz** [comment]
Thanks! I would like to do more (reorganize maps, add others...), but I'm not sure yet how to do this.
