### ISSUE TITLE
New CyclOSM site

### ISSUE THREAD

**Issue by u4y0u** [tankaru/OpenSwitchMaps#23]
Hello and thank you for this extension that I use as an amateur cartographer.

A new portal has appeared in the OSM family recently. This is CyclOSM. (Https://www.cyclosm.org)

The CyclOSM URLs are constructed as follows for example:
https://www.cyclosm.org/#map=15/47.9032/1.9035/cyclosm

Can you add this function to the Menu even though it has a lot of choices?

**Comment by tankaru** [comment]
CyclOSM added

**Comment by Scott8888** [comment]
https://github.com/tankaru/OpenSwitchMaps/issues/23
