### ISSUE TITLE
OpenSwitchMaps on Android

### ISSUE THREAD

**Issue by Bibi56** [tankaru/OpenSwitchMaps#24]
On mobile FireFox (FireFox or Fennec) you can use the plug-in.
Yeah!

It opens a new tab (why not), but clicking on a link (like Osmose) opens the link after a while but without real feedback and without closing the OpenSwitchMap page. It seems to work once.

A question for you @jazzzz ;-)

**Comment by jazzzz** [comment]
It seems that it's how these popups work on Firefox on Android: it always open in a new tab and it can only be closed by the user. When you click on a link, it opens the link, but you must close the tab manually. I don't know if there is a way to improve this.

**Comment by Bibi56** [comment]
@jazzzz OK :-(, but I've another idea: if you can't close the popup, maybe you can switch to the tab displaying the map. The result would be similar (as long as you can reuse the popup when you want to reopen the popup).

**Comment by tankaru** [comment]
For tablet and smartphone, I recommend OpenSwitchMaps Web.

**Comment by Bibi56** [comment]
@tankaru better with the link ;-) https://github.com/tankaru/OpenSwitchMapsWeb
