### ISSUE TITLE
Potential available maps

### ISSUE THREAD

**Issue by tankaru** [tankaru/OpenSwitchMaps#25]
I write some available maps those I'm considering whether to add.
It doesn't mean these will be added.

Any other unique maps?

- CyclOSM
  - Example: https://www.cyclosm.org/#map=15/47.9032/1.9035/cyclosm
  - Unique feature: Cycle infrastructure
  - Note: Japanese font is not supported
- OpenTopoMap
  - Example: https://opentopomap.org/#map=14/35.36522/138.73050
  - Unique feature: Elevation contour
- Mapcompare.jp
  - Example: https://mapcompare.jp/3/13/51.5061/-0.1208/osm/gRoad/mapSatellite
  - Unique feature: Map comparison with Google map support
- OSM Buildings
  - Example: https://osmbuildings.org/?lat=35.68321&lon=139.76309&zoom=16.0&tilt=30
  - Unique feature: 3D map
- Sentinel EO Browser
  - Example: https://apps.sentinel-hub.com/eo-browser/?lat=35.35773&lng=138.72475&zoom=14
  - Unique feature: Satellite sensing data
- Macrostrat
  - Example: https://macrostrat.org/map/#/z=3.6/x=138.6984/y=37.3612/bedrock/lines/
  - Unique feature: Geologic map
- Old maps online
  - Example: https://www.oldmapsonline.org/#bbox=138.69351621093747,35.14034523327696,140.2935162109375,36.135712802104365&q=&date_from=0&date_to=9999&scale_from=&scale_to=
  - Unique feature: Historic map
  - Note: BBox style

**Comment by tankaru** [comment]
Maps added

**Comment by tankaru** [comment]
- LocalWiki
`'https://nominatim.openstreetmap.org/reverse?format=json&lat=' + lat + '&lon=' + lon + '&zoom=10&addressdetails=1&accept-language=en'`
`window.location.href ='https://localwiki.org/_search/?q=' + data.display_name;`
- Anime location search
`https://seichimap.jp/spots?order=nearer&lat=35&lng=139`

**Comment by tankaru** [comment]
- OpenAerialMap
`https://map.openaerialmap.org/#/139.3341064453125,36.47872381162464,7`

**Comment by tankaru** [comment]
- Satellite Tracker 3D
`https://stdkmd.net/sat/?ll=37.57635762173198%2C135.25382555793894&lang=en`

**Comment by tankaru** [comment]
-Traze (public transit real-time location)
`https://traze.app/#/@51.977404,7.730029,4.94`

**Comment by tankaru** [comment]
地質図Navi
https://gbank.gsj.jp/geonavi/geonavi.php#7,37.141,139.681

**Comment by mpopp75** [comment]
Could mapy.cz be worth a consideration?

Example URL: https://en.mapy.cz/zakladni?x=14.9923937&y=49.1418711&z=14

**Comment by tankaru** [comment]
@mpopp75 
Thank you for your proposal of mapy.cz. I didn't know it.
It's sorry but I want to minimize the menu list, so I couldn't decide to add it or not right now.
Instead, I've added mapy.cz to the web version of OpenSwitchMaps.
You can access it via the right-bottom menu of OpenSwitchMaps v1.2.3, or add a special bookmarklet. See https://tankaru.github.io/OpenSwitchMapsWeb/index.html

**Comment by zaizone** [comment]
Hi, you could be interested by adding "viamichelin.com" in your tool.
I'm not sure but URL should be something like this : https://www.viamichelin.com/web/maps?position=-6.1756;106.8353;12
Nice work, cheers

**Comment by tankaru** [comment]
@zaizone
Thank you for your information.
As written above, I want to minimize the menu list, so I couldn't decide to add it or not right now.
Instead, I've added viamichelin.com to the web version of OpenSwitchMaps.

**Comment by tankaru** [comment]
Proposed maps are added to OpenSwitchMaps.
Check settings menu.
