### ISSUE TITLE
New column for local maps?

### ISSUE THREAD

**Issue by Bibi56** [tankaru/OpenSwitchMaps#28]
The fourth maps (maps.gsi.go.jp), those with JP and FR and the JapanMapCompare don't have a global coverage.
Adding a fourth column for non global maps may be useful, all ending (or starting) with the 2/3 letter code would help: probably we want to hide a whole range depending on a region (or instead make an accordion with the country as title?).

On the popup, a &#9881; icon could direct to the options would make more intuitive the tuning of the options (than right click on the earth icon). Anyway, each new version is better ;-).

**Comment by jazzzz** [comment]
> On the popup, a ⚙ icon could direct to the options would make more intuitive the tuning of the options (than right click on the earth icon)

Great idea, I added it in #29.
