### ISSUE TITLE
[Suggestion] user-defined links & database of maps

### ISSUE THREAD

**Issue by Wildersev** [tankaru/OpenSwitchMaps#34]
Thank you for great extension! It saves time and does what is supposed to do.
Just wanted to point out some inconveniences which stand in the way of comfortably using OpenSwitchMaps.
Currently only predefined maps are shown in dropdown list and this list doesn't include those from [OpenSwitchMaps Web](https://tankaru.github.io/OpenSwitchMapsWeb) version.
You have to click '_... and more maps_' than search and click the needed map and click again. It would be much easier to select needed maps from the complete list and use them without going to '_... and more maps_' menu.
Every region/country has lots of good quality local maps, so it's impossible to include all of them in one standard list. An option to add user-defined links to maps would greatly increase database of maps to choose from. Maybe this database can be stored in OpenSwitchMaps Web version, but again user should be able to add maps from this database to the dropdown menu.

**Comment by tankaru** [comment]
Thank you for your proposal.

I also want to add custom map in the extension version. But I don't have a good idea to implement it.

**Comment by Wildersev** [comment]
I'm not a good advisor at this, but you can take a look at how user created rules are managed in [Mouseover Popup Image Viewer](https://greasyfork.org/scripts/404-mouseover-popup-image-viewer) user script (it shows images and videos behind links and thumbnails). There is an [instruction for new users](https://w9p.co/userscripts/mpiv/host_rules.html) on how to create new rules and a [host rule repository](https://w9p.co/userscripts/mpiv/more_host_rules.html) of user suggested rules.
Maybe this can be a start point.

**Comment by tankaru** [comment]
OpenSwitchMaps web has custom map function.
