### ISSUE TITLE
Add 2gis maps

### ISSUE THREAD

**Issue by De-Luxis** [tankaru/OpenSwitchMaps#38]
https://2gis.com

A popular service in Russia.
It has the most detailed maps of major cities.

**Comment by tankaru** [comment]
It seems only Russia is supported.
If so, https://2gis.ru would be better?

**Comment by tankaru** [comment]
Updated.
Add https://2gis.ru from settings menu.

**Comment by De-Luxis** [comment]
> It seems only Russia is supported.
> If so, https://2gis.ru would be better?

No, some European cities are also supported.

for example: https://2gis.cz/praha?m=14.422337%2C50.088451%2F16.82

**Comment by tankaru** [comment]
Then, do you think https://2gis.com is better?
(Current version opens https://2gis.ru )

**Comment by De-Luxis** [comment]
> Then, do you think https://2gis.com is better?
> (Current version opens https://2gis.ru )

Yes. There, an automatic redirect to the desired domain depending on the IP address.

**Comment by tankaru** [comment]
OK.
I will change to  https://2gis.com in the next version.
