### ISSUE TITLE
include waze editor

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [tankaru/OpenSwitchMaps#40]
https://www.waze.com/pt-BR/editor?env=row&lon=-48.05341&lat=-16.05356&zoom=7

**Comment by tankaru** [comment]
already you have.
check settings menu.

**Comment by erickdeoliveiraleal** [comment]
but it would be better if it goes direct to waze editor, instead simple map, it takes a lot of time to load and switch between.

**Comment by erickdeoliveiraleal** [comment]
if you can add it, please make it default to zoom level 7.

**Comment by erickdeoliveiraleal** [comment]
i think it's would better to make it default zoom = 7, please.

**Comment by tankaru** [comment]
OK.
I updated it on version 1.3.2
