### ISSUE TITLE
[Suggestion] adding Komoot's Routeplanner

### ISSUE THREAD

**Issue by bevoorrading** [tankaru/OpenSwitchMaps#44]
Hi,

Thanks for the great add-on. 

Any possibility of adding Komoot's Routeplanner? Shouldn't be too difficult, it uses the same location and zoom level in the url as Google Maps. And it can be quite useful to look at pictures people added to a place on Komoot.

Thanks

**Comment by limex** [comment]
I forged this repo. Among other fixes I added komoot. If you are willing to build the code yourself: https://github.com/limex/OpenSwitchMaps

**Comment by tankaru** [comment]
Thanks for your proposal. I've added komoot to the list.
It will be added to the extension soon.
