### ISSUE TITLE
[Suggestion] add OSM-fr local chapter

### ISSUE THREAD

**Issue by Marc-marc-marc** [tankaru/OpenSwitchMaps#46]
url is for ex https://tile.openstreetmap.fr/?zoom=6&lat=46.4&lon=2.3508&layers=B00000000FFFFFF (layer is optional, default to osmfr style)

**Comment by tankaru** [comment]
I'm sorry. I missed this post.

When I accessed this link, it gave me ERR_CONNECTION_TIMED_OUT.

https://tile.openstreetmap.fr/?zoom=6&lat=46.4&lon=2.3508&layers=B00000000FFFFFF

**Comment by Marc-marc-marc** [comment]
yes there was a small hardware failure during the weekend, it is now resolved

**Comment by tankaru** [comment]
I added a link. However, the coordinates are not updated, so it is not possible to jump from osm.fr to an external site.

**Comment by Marc-marc-marc** [comment]
thanks !
the coordinates are updated when you click on permalink.
I'm going to find out if this update is possible automatically.
