### ISSUE TITLE
Please add support for the National Library of Scotland's historic maps

### ISSUE THREAD

**Issue by pigsonthewing** [tankaru/OpenSwitchMaps#48]
Please add support for the National Library of Scotland's historic maps.
 
 URLs take the form:

https://maps.nls.uk/geo/explore/#zoom=17&lat=52.56060&lon=-1.92500&layers=6&b=1

or:

https://maps.nls.uk/geo/explore/side-by-side/#zoom=17&lat=52.56057&lon=-1.92498&layers=6&right=osm

**Comment by tankaru** [comment]
The former link has been added. Please wait for updates.
