### ISSUE TITLE
[Suggestion] Add Yandex.Panorams

### ISSUE THREAD

**Issue by deevroman** [tankaru/OpenSwitchMaps#56]
This is a service from Yandex.maps, an analogue of Google Street View
<img width="368" alt="Снимок экрана 2021-09-06 в 23 51 24" src="https://user-images.githubusercontent.com/25708359/132259920-ee04fd8f-c02e-4252-9763-0d0b76fefabd.png">

**Comment by tankaru** [comment]
done
