### ISSUE TITLE
[Suggestion] Please add RapiD editor

### ISSUE THREAD

**Issue by govvin** [tankaru/OpenSwitchMaps#62]
Hello there. Thanks for making this awesome utility, which I find very useful, and use it often. 😉 

Can you please consider adding a switch link to the [RapiD editor](https://mapwith.ai/rapid)? This is a fork of the OpenStreetMap iD editor, built for helping mappers utitize MapWithAI detection of highways and buildings.

**Comment by tankaru** [comment]
RapiD editor is already included. Check settings ⚙️.

**Comment by govvin** [comment]
Oh, it is there! I'm so sorry for the bother.

I thought it wasn't available because in Firefox, the preference for the add-on looked like this
![image](https://user-images.githubusercontent.com/5821688/153116020-3ae10728-c98c-453e-80ba-f7d395733752.png)

One has to scroll further to the right to find more options, which I didn't do.  

Thank you for your awesome work.
