### ISSUE TITLE
More direct links

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [tankaru/OpenSwitchMaps#72]
In the [OSM Smart Menu ](https://github.com/jgpacker/osm-smart-menu) the Sentinel link directly takes the images, it is much faster. Here it could be as well. It takes a long time for when I'm going to map in OSM I have to keep selecting several options in Sentinel Browser.

**Comment by tankaru** [comment]
OpenSwitchMaps supports "EO Browser".
OSM smart menu supports "Playground".

Do you want OpenSwitchMaps support "Playground" also?

There is no "default" imagery of EO Browser, so OpenSwitchMaps doesn't show imagery at first.
