### ISSUE TITLE
Add support for local map "BayernAtlas"

### ISSUE THREAD

**Issue by FloEdelmann** [tankaru/OpenSwitchMaps#76]
URL: https://www.geoportal.bayern.de/bayernatlas/?topic=ba&lang=de&bgLayer=atkis&catalogNodes=11&E=604510.08&N=5337130.40&zoom=3
- unfortunately, the `N` and `E` URL parameters are not simply latitude and longitude
- zoom levels 1 until 15
- the other URL parameters can be ignored

```js
{
	  name: "BayernAtlas",
	  category: LOCAL_CATEGORY,
	  default_check: false,
	  domain: "www.geoportal.bayern.de",
	  description: "der Kartenviewer des Freistaates Bayern",
	  // getUrl(…): ?
	  // getLatLonZoom(…): ?
}
```

**Comment by tankaru** [comment]
Thanks for your proposal.
But sorry I couldn't find a good conversion method between GK4 and WGS84.

**Comment by fxedel** [comment]
Have a look at Wikimedia's GeoHack tool: https://geohack.toolforge.org/geohack.php?pagename=M%C3%BCnchen&language=de&params=48.137222222222_N_11.575555555556_E_region:DE-BY_type:city(1487708)

It tells us that there's an URL parameter in BayernAtlas for using the standard WGS 48 coordinates: https://geoportal.bayern.de/bayernatlas?lon=11.575556&lat=48.137222&zoom=10

Implementing this in OpenSwitchMaps should be much easier.

It may also be worth implementing the other map services linked by GeoHack, e.g. geoportal.de, NiedersachsenViewer and so on.

We _could_ also add GeoHack itself as new "map"

**Comment by tankaru** [comment]
Thanks.
I'll add BayernAtlas.
And I'll try to add lang parameter to GeoHack.

**Comment by tankaru** [comment]
BayernAtlas updated
