### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by govvin** [tankaru/OpenSwitchMaps#78]
Would it be possible for you to add a "copy coordinates" to clipboard feature? I know that it doesn't really "switch" to anything, but sometimes, all you need are coordinates. :sweat_smile:

**Comment by tankaru** [comment]
Is there a good format for coordinates?

**Comment by govvin** [comment]
latitude, longitude (e.g. "8.4754,124.6504") in decimal degrees works in OpenStreetMap, and Google Maps, but some systems prefer the reverse (lon,lat).

**Comment by tankaru** [comment]
So, even when "8.4754,124.6504" is copied to the clipboard, we can't find which figure is lat/lon.

**Comment by govvin** [comment]
Yes, but perhaps you'll find some inspiration from how Maproulette works around the ambiguity:

> Coordinates are labeled as "Lat/Lon" or "Lon/Lat", depending on user's preference
> ![image](https://user-images.githubusercontent.com/5821688/179320690-ac81c263-57ad-4d1f-a9b1-51dd1b8646b0.png)

A user can switch between the two anytime.

**Comment by tankaru** [comment]
Ok I use Maproulette format.

**Comment by tankaru** [comment]
I tried it, but it was not possible under current system.
