### ISSUE TITLE
Sometimes does not show map switcher on Yandex Maps

### ISSUE THREAD

**Issue by Self-Perfection** [tankaru/OpenSwitchMaps#80]
Example Yandex Maps URL without the switcher:
https://yandex.ru/maps/143/kyiv/?ll=30.523914%2C50.450183&mode=search&sll=30.523550%2C50.450444&text=50.450444%2C30.523550&z=17.99

**Comment by tankaru** [comment]
Thanks I fixed it. Wait for app update.
