### ISSUE TITLE
pic4carto is offline

### ISSUE THREAD

**Issue by fxedel** [tankaru/OpenSwitchMaps#95]
See https://projets.pavie.info/pic4carto/

**Comment by tankaru** [comment]
Thanks. It seems Pic4Carto has been stopped and Pic4Review has started.
https://twitter.com/PanierAvide/status/1509152672569516039

I'll change Pic4Carto  to Pic4Review.

**Comment by tankaru** [comment]
Oh, it seems Pic4Review doesn't have a functionality to view map.
I'll just deactivate Pic4Carto.

**Comment by tankaru** [comment]
done
