### ISSUE TITLE
Add MapComplete to the list of supported maps

### ISSUE THREAD

**Issue by ygra** [tankaru/OpenSwitchMaps#99]
[MapComplete](https://mapcomplete.osm.be) offers thematic maps for various themes, all based on OpenStreetMap. It also allows editing them conveniently.

**Comment by tankaru** [comment]
Would you give me a url with lat, lon, zoom ?
I couldn't find it.

**Comment by ygra** [comment]
Ah, MapComplete is likely trickier than other options, in that there are multiple different maps. They all follow the same pattern:

```
https://mapcomplete.osm.be/{theme}.html?z={zoom}&lat={lat}&lon={lon}
```

I'm not sure where a full list of themes can be found, though, except the list on the home page.

**Comment by tankaru** [comment]
Sorry, {theme} pattern is not supported.
